mybatis:
  mapper-locations: classpath:/mapper/*.xml

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/idthub
    username: testuser1
    password: 1234
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  jwt:
    header: Authorization
